all: tutorial2/tutorial2_main tutorial3/tutorial3_main tutorial4/tutorial4_main tutorial5/tutorial5_main tutorial6/tutorial6_main tutorial7/tutorial7_main tutorial8/tutorial8_main tutorial9/tutorial9_main tutorial10/tutorial10_main tutorial11/tutorial11_main tutorial12/tutorial12_main tutorial13/tutorial13_main tutorial14/tutorial14_main tutorial15/tutorial15_main tutorial16/tutorial16_main

tutorial2/tutorial2_main: tutorial2/main.rs
	rustc tutorial2/main.rs -o tutorial2/tutorial2_main
	
tutorial3/tutorial3_main: tutorial3/main.rs
	rustc tutorial3/main.rs -o tutorial3/tutorial3_main
	
tutorial4/tutorial4_main: tutorial4/main.rs
	rustc tutorial4/main.rs -o tutorial4/tutorial4_main
	
tutorial5/tutorial5_main: tutorial5/main.rs
	rustc tutorial5/main.rs -o tutorial5/tutorial5_main
	
tutorial6/tutorial6_main: tutorial6/main.rs
	rustc tutorial6/main.rs -o tutorial6/tutorial6_main
	
tutorial7/tutorial7_main: tutorial7/main.rs
	rustc tutorial7/main.rs -o tutorial7/tutorial7_main
	
tutorial8/tutorial8_main: tutorial8/main.rs
	rustc tutorial8/main.rs -o tutorial8/tutorial8_main
	
tutorial9/tutorial9_main: tutorial9/main.rs
	rustc tutorial9/main.rs -o tutorial9/tutorial9_main
	
tutorial10/tutorial10_main: tutorial10/main.rs
	rustc tutorial10/main.rs -o tutorial10/tutorial10_main
	
tutorial11/tutorial11_main: tutorial11/main.rs
	rustc tutorial11/main.rs -o tutorial11/tutorial11_main
	
tutorial12/tutorial12_main: tutorial12/main.rs
	rustc tutorial12/main.rs -o tutorial12/tutorial12_main
	
tutorial13/tutorial13_main: tutorial13/main.rs
	rustc tutorial13/main.rs -o tutorial13/tutorial13_main
	
tutorial14/tutorial14_main: tutorial14/main.rs
	rustc tutorial14/main.rs -o tutorial14/tutorial14_main
	
tutorial15/tutorial15_main: tutorial15/main.rs
	rustc tutorial15/main.rs -o tutorial15/tutorial15_main
	
tutorial16/tutorial16_main: tutorial16/main.rs
	rustc tutorial16/main.rs -o tutorial16/tutorial16_main
	
clean:
	rm -f tutorial2/tutorial2_main tutorial3/tutorial3_main tutorial4/tutorial4_main tutorial5/tutorial5_main tutorial6/tutorial6_main tutorial7/tutorial7_main tutorial8/tutorial8_main tutorial9/tutorial9_main tutorial10/tutorial10_main tutorial11/tutorial11_main tutorial12/tutorial12_main tutorial13/tutorial13_main tutorial14/tutorial14_main tutorial15/tutorial15_main tutorial16/tutorial16_main

